### ISSUE TITLE
[Feature] Show route grade instead of n/a

### ISSUE THREAD

**Issue by frspp** [jossi87/climbing-web#112]
When adding a tick and choosing "n/a" for grade tick will be shown as n/a in my stats too. I would prefer grade to be shown in route's grade - be it FA grade or the other grade shown on route's details 

For example:
Psilocin FA 6c+, now 7a
https://klatreforer.tromsoklatring.no/problem/6244

**Comment by jossi87** [comment]
Hi

The personal ticklist (e.g. https://klatreforer.tromsoklatring.no/user/4923) always shows the grade that the user has suggested. I don't see why n/a should be substituted with a common consensus (based on fa-tick and other ticks) when the user has chosen to give the n/a-grade.
In this [example](https://brattelinjer.no/problem/9814) a user has graded the route with n/a to indicate that he took a fall and therefore did not actually send the route. It would be strange if this was changed to 8- in his tick list.
I understand that it's difficult to give a good grade suggestion on onsights, but that is part of the game. It's up to you if you want to tick it with the consensus, change it, or just leave tick it as n/a. The users stats should reflect the users personal grades (in my opinion).

Feel free to share your own thoughts here, I just can't see a good reason to change this behavior for now 🙂

**Comment by jossi87** [comment]
I understand your point, but that is how it feels for everyone when they reach a new level. You should either trust the consensus, or downgrade if you don't feel it's correct.
The example I sent is not a todo. This was an old AID-route that has now been sent in free. One in the FFA-team (first free ascent) had one fall in one of the rope lengths and therefore wrote n/a. I think that makes more sense than ticking with grade, or not ticking at all.
Back to the route in question (Psilocin). I would tick in 7a or 6c+, and keep it in mind for later. You can always upgrade or downgrade your personal opinion later on. And if you don't want to make up your mind now just keep it as n/a until you have more experience and change it later.
As mentioned earlier, you have to do what feels correct for you, grading is never easy. And every grade (both fa and tick) is a feeling more than exact science.

**Comment by evancharlton** [comment]
As someone who's relatively newish to climbing, I think I understand where @frspp is coming from -- when I send a route, I'm happy to trust the general consensus of the difficulty. If it's downgraded later, I'm okay with my profile being updated to reflect that -- _I had no opinion at the time_.

In short: the default tick modal looks like this:
![image](https://github.com/jossi87/climbing-web/assets/418560/7b4aa958-e27b-4a4f-a5c7-a6b766a2afd4)

However, there's a bit of subtle information lost here: **I didn't choose 7/7+ (6c+)**. I left it at the default.

It'd be nice if we could retain that subtlety in the data model.

**Comment by jossi87** [comment]
Fair point, I am still not 100% convinced though. But on the other hand I don't mind implementing this feature, it will just take some time. There are a lot of queries that has to change in addition to UI-changes.

There are in total 41.390 individual ticks in the database now (bouldering + climbing). Most of these are just left as default without a specific opinion. A property like this can not change the past, and needs to be implemented in a way that does not alter the behavior of the site more than necessary.

I have a couple of comments, can you both look at them and give me feedback on what you think?

- Tick-UI (photo Evan added in the last comment): It's important to keep ticking efficient. Today you have to set rating, the other fields can be left as default. I don't want to make grade mandatory as well, as this will make it even more time consuming for users to tick routes. But I suggest adding a checkbox: "No opinion regarding grade" that is not toggled by default. If a user presses this the grade is grayed out and not saved on the tick.
- Calculation of consensus grade: Ignore ticks with "No opinion regarding grade" toggled on
- Everywhere where the tick is listed (problem, frontpage, ticks etc.): List the tick with consensus grade and a "No opinion regarding grade"-label
- Statistics (diagram in users page): Count tick with consensus grade instead of personal grade

**Comment by jossi87** [comment]
Agree on both points (consistent UI + order of grades).
I'll put this on my todo-list. I have quite a few tasks I want to finish before doing this, I also have a "summer vacation" coming up in a couple of weeks. But at least it's on the todo-list now 🙂

**Comment by jossi87** [comment]
@frspp : This is implemented now. Can you take a look at it and see if it works as you want?
