### ISSUE TITLE
[Bug] Baksida (sector #3070) is reported as facing south

### ISSUE THREAD

**Issue by evancharlton** [jossi87/climbing-web#120]
**Describe the bug**
On the `/problems` page, the Baksida sector is marked a facing south. However, it faces north.

![image](https://github.com/jossi87/climbing-web/assets/418560/6de2114f-c603-4ccb-b245-5c0c25e17b40)

**To Reproduce**
1. Go to 'https://klatreforer.tromsoklatring.no/problems
2. Scroll to Baksida

**Expected behavior**
It should be marked as facing north

**Screenshots**
![image](https://github.com/jossi87/climbing-web/assets/418560/4725855c-4c2e-448d-b9b8-ffe87ff38f96)

**Comment by jossi87** [comment]
The wall direction is calculated by comparing elevation on the four corners of a sector outline. Baksida should indeed be north-facing, but the reason why the algorithm gets this wrong is that the polygon is drawn wrong.
I have updated the db and ws today so that is also returns elevation on each point (the plan going forward is to use elevation in other parts of the site, for example an altitude graph for approach - but this is off topic 🙂).
You can now show elevation when viewing outlines. The two lower coordinates on the outline in question have a lower elevation than the two upper:
![image](https://github.com/jossi87/climbing-web/assets/17472908/2a900f78-3848-40a9-8ed1-7055a888223a)

It can be fixed by redrawing the outline. Close this bug if this answers your questions, or update me with more information

**Comment by evancharlton** [comment]
I spent some time playing with it, and I haven't been able to correct it. If I had to guess, the topo granularity isn't fine-grained enough to know that it's a north-facing slab in the middle of a south-facing hillside.

**Comment by jossi87** [comment]
Yeah, I tried it myself and I could not get it to work either. Agree with your assumption here. Unfortunately not much I can do here ☹️
I guess the best solution in this case is to only use three points on the sector outline. Four is required to calculate wall direction, so after changing this one to three points the wall direction is kept blank.

**Comment by evancharlton** [comment]
I alluded to this in an email thread, but it would be nice to have this field able to be manually-set (and computed if there's no human input). This is the kind of data that is possible to spend a lot of computing power on and be mostly right .. or have one human enter it once and be done with it forever 😀

**Comment by jossi87** [comment]
Good point, I agree. Will put it on my todo-list and keep this open until it's implemented.
